export const routerLinks = {
  Login: '/login',
  ActiveAccount:'/active_account',
  CreateAccount: '/createaccount',
  SubsidyRequest: '/subsidyrequest',
  SubsidyReview: '/subsidyreview',
  ForgotPass: '/forgotpass',
  ResetPass: '/resetpass',

  Dashboard: '/account/dashboard',
  Admin: '/administrator/admin',
  Appointments: '/administrator/appointments',
  SchoolsList: '/administrator/schoolslist',
  FlagList: '/administrator/flaglist',
  ConsultationRequests: '/administrator/consultationrequests',
  SchedulingCenter: '/administrator/schedulingcenter',
  UserManager: '/administrator/usermanager',
  SystemSetting: '/administrator/systemsetting',
  SubsidyManager: '/administrator/subsidymanager',
  Statistics: '/administrator/statistics',
  Changeprofile: '/account/changeprofile',
  Pages403: '/widget/403',
  Pages404: '/widget/404',
  Pages500: '/widget/500',
  Blank: '/widget/blank',
  Home: '/home/home',
};
