
export const userSignUp = 'users/signup'
export const checkEmailRegistered = 'users/check_email_registered'
export const getDependents = 'users/get_dependents'
export const deletePrivateNote = 'users/delete_private_note'
export const updatePrivateNote = 'users/update_private_note'
export const createPrivateNote = 'users/create_private_note'
export const changePassword = 'users/change_password'

export const getAppointmentsForAdmin = 'admin/get_appointments'
export const getAppointmentsInMonthForAdmin = 'admin/get_appointments_in_month'
export const getDefaultDataForAdmin = 'admin/get_default_data'
export const searchProvidersForAdmin = 'admin/search_providers'
export const getUsers = 'admin/get_users'
export const activateUser = 'admin/activate_user'
export const getSettings = 'admin/get_settings'
export const updateSettings = 'admin/update_settings'

export const getDefaultValuesForConsultant = 'consultants/get_default_values_for_consultant'
export const getAppointmentsForConsultant = 'consultants/get_my_appointments'
export const getAppointmentsInMonthForConsultant = 'consultants/get_my_appointments_in_month'

export const getCommunitiServer = 'schools/get_list_communites'
export const getSchoolInfos = 'schools/get_school_infos'

export const getAppointmentsForProvider = 'providers/get_my_appointments'
export const getAppointmentsInMonthForProvider = 'providers/get_my_appointments_in_month'
export const getCityConnections = 'providers/get_city_connections'
export const getDefaultValueForProvider = 'providers/get_default_values_for_provider'
export const getReviewInfoForProvider = 'providers/get_review_info'
export const uploadTempW9FormForProvider = 'providers/upload_temp_w9_form'
export const checkNotificationForProvider = 'providers/check_notification'
export const closeAppointmentForProvider = 'providers/close_appointment'
export const declineAppointmentForProvider = 'providers/decline_appointment'
export const leaveFeedbackForProvider = 'providers/leave_feedback'
export const cancelAppointmentForProvider = 'providers/cancel_appoint'
export const getMyProviderInfo = 'providers/get_my_provider_info'

export const getAppointmentsForParent = 'clients/get_my_appointments'
export const getAppointmentsInMonthForParent = 'clients/get_my_appointments_in_month'
export const createAppointmentForParent = 'clients/create_appoinment'
export const getAllSchoolsForParent = 'clients/get_all_schools'
export const getDefaultValueForClient = 'clients/get_default_value_for_client'
export const checkNotificationForClient = 'clients/check_notification'
export const closeNotificationForClient = 'clients/close_notification'
export const cancelAppointmentForParent = 'clients/cancel_appoint'
export const updateAppointmentNotesForParent = 'clients/update_appointment_notes'
export const rescheduleAppointmentForParent = 'clients/reschedule_appointment'
export const getAllConsultantForParent = 'clients/get_all_consultants'
export const getConsultationsForDependent = 'clients/get_consultations_for_dependent'
export const uploadDocumentForParent = 'clients/upload_document'
export const createSubsidyRequest = 'clients/create_subsidy_request'
export const requestFeedbackForClient = 'clients/request_feedback'
export const getChildProfile = 'clients/get_child_profile'
export const getParentProfile = 'clients/get_parent_profile'
